#!/bin/bash
set -e

OUTPUT_FILE="src/templates/notebook-template.js"
SOURCE_DIR="test-notebook"

echo "Generating notebook template from $SOURCE_DIR..."

# Create output directory if needed
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Start the JavaScript file
cat > "$OUTPUT_FILE" << 'HEADER'
/**
 * @fileoverview Bundled notebook template for scaffolding new projects.
 * Generated by generate-template-notebook.sh - DO NOT EDIT MANUALLY
 */

export const NOTEBOOK_TEMPLATE = {
HEADER

# Find all files and process them
find "$SOURCE_DIR" -type f | sort | while IFS= read -r filepath; do
  # Get relative path
  relpath="${filepath#$SOURCE_DIR/}"
  
  # Escape the path for JavaScript
  escaped_path=$(printf '%s' "$relpath" | sed 's/\\/\\\\/g; s/"/\\"/g')
  
  # Read and escape content - handle special chars
  escaped_content=$(cat "$filepath" | \
    sed 's/\\/\\\\/g' | \
    sed 's/"/\\"/g' | \
    sed 's/	/\\t/g' | \
    awk '{printf "%s\\n", $0}' | \
    sed '$ s/\\n$//')
  
  # Add to the template object
  echo "  \"$escaped_path\": \"$escaped_content\"," >> "$OUTPUT_FILE"
done

# Close the object
echo "};" >> "$OUTPUT_FILE"

echo "✓ Generated $OUTPUT_FILE"
file_count=$(grep -c '":' "$OUTPUT_FILE" || echo "0")
echo "✓ Template contains $file_count files"

